### ISSUE TITLE
career support - trello - Trello for jobs

### ISSUE THREAD

**Issue by ktrammell95** [dawnribeiro/assignments#16]
# Create a Trello card for one job

In this assignment, you will create a Trello card for a job that you found interesting. This can be for your dream job or just something that sounded interesting to you.

## Card Requirements

- [ ] Company name - job title
- [ ] Description of the company
- [ ] Company website link
- [ ] Location
- [ ] Link to the job description

- Add comments:
- [ ] What is their narrative?
- [ ] Why do you like this company?
- [ ] Why did you like this posting?
- [ ] How might you benefit them?

## Turning in your assignment

- To turn in this assignement you will move your card to "Ready for Rec" and tag Katherine (@ktrammellsdg) in a comment on that card with the wording "Ready for a Rec"
- Copy and paste the link to your card as a comment on this issue

## Due Date

- This assignment is due by 9 am on Friday, May 31st.

**Comment by dawnribeiro** [comment]
https://trello.com/b/BfFiz0Su/dawn-job-search

**Comment by ktrammell95** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBXZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9ab12a6cb8616834a8b7e838629a5c8c61b5f7a3/giphy-14.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/79)**__
