### ISSUE TITLE
week 05 - day 02 - favorite music

### ISSUE THREAD

**Issue by mdewey** [dawnribeiro/assignments#18]
# Music Madness

For tonight, I want you to show off your music artists. You will be creating a multiple page app, using react-router.

## Objectives

- Create a SPA, with a few pages
- Deploying your website

## Requirements

- Build a website that has 4 pages.
  - 1 landing
  - a page for your top three favorite bands.

### Explorer Mode

- [ ] Add `react-router-dom` to your project.
- [ ] Create a Landing page that displays a short description of all three of your bands
- [ ] Build 3 band pages. These pages should have a
  - [ ] a band picture
  - [ ] band name
  - [ ] Latest Album information
- [ ] Each page should have a nav bar that allows the user to browse from page to page
- [ ] Deploy your site

_TIP_: for Explorer mode focus on getting the router set up and linking the pages to each other.

### Adventure Mode

- [ ] Instead of hard coding the URL, try to use parameters, components and JSON file to supply navigation for your site.

### Epic Mode

- [ ] Add integrations from [Last.fm API](https://www.last.fm/api). This API has a bunch of features. Go crazy, the sky is the limit.

## Additional Resources

- [npm react-router-dom](https://www.npmjs.com/package/react-router-dom)
- `yarn add react-router-dom`

**Comment by dawnribeiro** [comment]
https://github.com/dawnribeiro/favorite-music

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBYUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6653a5b4c8e877384d759556a53bfc97521ca49f/giphy-17.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/82)**__
