### ISSUE TITLE
week 07 - day 01  -  INSERT INTO Student (knowledge) VALUES ('SQL')

### ISSUE THREAD

**Issue by mdewey** [dawnribeiro/assignments#26]
# INSERT INTO Student (knowledge) VALUES ('SQL')

Every application uses data in some way. This will help you set up your development environment as well as get used to querying databases.

## Objectives

- Install Postgres
- Create a database for Employees
- Write some queries to use the database

## Requirements

- Set up postgres by following [these directions.](https://suncoast.io/handbook/tools/postgresql/)

### Explorer Mode

- [x] Install Postgres
- [x] Create a database: `company_database`
- [ ] Create a table: `employees`
- [ ] Add the following columns to the table, Use your best judgement for data types

  - full_name
  - salary
  - job_position
  - phone_extension
  - part_time

- [ ] Create queries that can do the following:

  - [ ] Select all columns for all employees
  - [ ] Select only the Full Name and Phone Extension for only Full Time employees
  - [ ] Insert a new part time employee, as a software developer, part time, with a salary of 450
  - [ ] Update all employees that are the cooks to have a salary of 500
  - [ ] Delete all employees that have the full name of "Lazy Lynn"
  - [ ] Update all employees to be full time
  - [ ] Add a column to the table: `parking_spot_number` as a string that up to 10 characters long

- [ ] Turn in the above queries as a gist

### Adventure Mode

- [ ] Work on your final project

### Epic Mode

- [ ] Investigate working with C# and Postgres, HINT: `entity framework core`

## Additional Resources

- [PostgreSQL 10 Documentation](https://www.postgresql.org/docs/10/static/index.html)

## Recommended Practice:

- For more practice, Hackerrank has a [SQL Track](https://www.hackerrank.com/domains/sql)

**Comment by dawnribeiro** [comment]
https://gist.github.com/dawnribeiro/154e6a955f7f1175aace8a1791957b6b

**Comment by mdewey** [comment]
I see you have have the gist of I am looking for, but I would like to see the queries run without errors. Let me know if you have questions or need any help

**Comment by mdewey** [comment]
Your homework was marked: **Acceptable**

![hmmm..acceptable! ](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBSZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dbf0839075b0c873bc9d53d1b39f6ae9204934b9/acceptable.gif)
> &ldquo;hmmm..acceptable! &rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/60)**__
