### ISSUE TITLE
week 08 - day 01 - explosive api

### ISSUE THREAD

**Issue by mdewey** [dawnribeiro/assignments#30]
# Explosion Api

You have already solved the `explosion` and `mumbling` katas. The client loves your solution so much that they want you to turn it into an API us on the web.

For tonight, I want you to create a simple API with two endpoints, one for the `explosion` and one for the `mumbling`.

## Objectives

- Create a simple API
- Practice problem solving

## Requirements

- Install the `sdg-api` template using the command `dotnet new -i SDG.templates.Web.API`
- Create 2 endpoints, `/api/mumbling` and `api/explosion`, that are based off of the katas,`[https://www.codewars.com/kata/mumbling](https://www.codewars.com/kata/mumbling)` and `[https://www.codewars.com/kata/digits-explosion](https://www.codewars.com/kata/digits-explosion)` respectfully.

### Explorer Mode

- [ ] Create a new `sdg-web` api project
- [ ] Create a endpoint for the `mumbling` endpoint
  - [ ] Create a new Controller called `MumblingController`
  - [ ] This will have one `HttpGet`
  - [ ] The one get will accept a string
  - [ ] This endpoint will take the string passed to it, manipulate according to the kata [https://www.codewars.com/kata/mumbling](https://www.codewars.com/kata/mumbling) and return the result
  - [ ] This will return a `ActionResult<string>`
- [ ] Create a endpoint for the `explosion` endpoint
  - [ ] Create a new Controller called `ExplosionController`
  - [ ] This will have one `HttpGet`
  - [ ] The one get will accept a string
  - [ ] This endpoint will take the string passed to it, manipulate according to the kata [hhttps://www.codewars.com/kata/digits-explosion](hhttps://www.codewars.com/kata/digits-explosion) and return the result
  - [ ] This will return a `ActionResult<string>`
- [ ] turn in your project via github with a .gitignore.

### Adventure Mode

- [ ] Ensure your instructor has seen and approved your wireframes for your capstone.
- [ ] Work on the HTML for your capstone.
- [ ] Work on your Resume for Career Support.

**Comment by dawnribeiro** [comment]
https://github.com/dawnribeiro/explosion

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBUdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a60036409d53f8b1c2804766f540dccb4215ec74/giphy-3.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/68)**__
